export interface Intinerario {
    bairro: string;
    doca: string;
    itinerario: number;
}

export const Intinerarios = [
    { bairro: "BETANIA", doca: "36", itinerario: 20 },
    { bairro: "CACHOEIRINHA", doca: "26", itinerario: 16 },
    { bairro: "CENTRO", doca: "25", itinerario: 15 },
    { bairro: "CRESPO", doca: "36", itinerario: 20 },
    { bairro: "DISTRITO INDUSTRIAL I", doca: "32", itinerario: 22 },
    { bairro: "EDUCANDOS", doca: "36", itinerario: 19 },
    { bairro: "JAPIIM", doca: "28", itinerario: 18 },
    { bairro: "MORRO DA LIBERDADE", doca: "36", itinerario: 19 },
    { bairro: "PETROPOLIS", doca: "27", itinerario: 17 },
    { bairro: "PRACA 14", doca: "26", itinerario: 16 },
    { bairro: "PRESIDENTE VARGAS", doca: "26", itinerario: 16 },
    { bairro: "SANTA LUZIA", doca: "36", itinerario: 19 },
    { bairro: "SAO FRANCISCO", doca: "27", itinerario: 17 },
    { bairro: "SAO LAZARO", doca: "36", itinerario: 20 },
    { bairro: "VILA BURITI", doca: "36", itinerario: 20 },
    { bairro: "COLONIA OLIVEIRA MACHADO", doca: "36", itinerario: 19 },
    { bairro: "APARECIDA", doca: "25", itinerario: 15 },
    { bairro: "ARMANDO MENDES", doca: "33", itinerario: 22 },
    { bairro: "COLONIA ANTONIO ALEIXO", doca: "32", itinerario: 21 },
    { bairro: "COROADO", doca: "34", itinerario: 23 },
    { bairro: "DISTRITO INDUSTRIAL II", doca: "33", itinerario: 22 },
    { bairro: "GILBERTO MESTRINHO", doca: "37", itinerario: 30 },
    { bairro: "JORGE TEIXEIRA", doca: "38", itinerario: 26 },
    { bairro: "MAUAZINHO", doca: "32", itinerario: 21 },
    { bairro: "PURAQUEQUARA", doca: "32", itinerario: 31 },
    { bairro: "SAO JOSE OPERARIO", doca: "35", itinerario: 24 },
    { bairro: "TANCREDO NEVES", doca: "29", itinerario: 25 },
    { bairro: "ZUMBI DOS PALMARES", doca: "33", itinerario: 22 },
    { bairro: "ADRIANOPOLIS", doca: "16", itinerario: 7 },
    { bairro: "ALEIXO", doca: "15", itinerario: 6 },
    { bairro: "CHAPADA", doca: "10/11", itinerario: 5 },
    { bairro: "FLORES", doca: "08/09", itinerario: 4 },
    { bairro: "NOSSA SENHORA DAS GRACAS", doca: "16", itinerario: 7 },
    { bairro: "SAO GERALDO", doca: "16", itinerario: 7 },
    { bairro: "PARQUE 10 DE NOVEMBRO", doca: "10/11", itinerario: 5 },
    { bairro: "ALVORADA", doca: "17", itinerario: 8 },
    { bairro: "DA PAZ", doca: "18", itinerario: 9 },
    { bairro: "DOM PEDRO", doca: "17", itinerario: 8 },
    { bairro: "PLANALTO", doca: "18", itinerario: 9 },
    { bairro: "REDENÇÃO", doca: "18", itinerario: 9 },
    { bairro: "CIDADE DE DEUS", doca: "39", itinerario: 27 },
    { bairro: "CIDADE NOVA", doca: "06/07", itinerario: 3 },
    { bairro: "COLONIA SANTO ANTONIO", doca: "04/05", itinerario: 2 },
    { bairro: "COLONIA TERRA NOVA", doca: "04/05", itinerario: 2 },
    { bairro: "LAGO AZUL", doca: "30/31", itinerario: 1 },
    { bairro: "MONTE DAS OLIVEIRAS", doca: "30/31", itinerario: 1 },
    { bairro: "NOVA CIDADE", doca: "23", itinerario: 29 },
    { bairro: "NOVO ALEIXO", doca: "40", itinerario: 28 },
    { bairro: "NOVO ISRAEL", doca: "04/05", itinerario: 2 },
    { bairro: "SANTA ETELVINA", doca: "30/31", itinerario: 1 },
    { bairro: "COMPENSA", doca: "22", itinerario: 12 },
    { bairro: "VILA DA PRATA", doca: "24", itinerario: 14 },
    { bairro: "GLORIA", doca: "24", itinerario: 14 },
    { bairro: "LIRIO DO VALE", doca: "21", itinerario: 11 },
    { bairro: "NOVA ESPERANCA", doca: "21", itinerario: 11 },
    { bairro: "PONTA NEGRA", doca: "19/20", itinerario: 10 },
    { bairro: "SANTO AGOSTINHO", doca: "21", itinerario: 11 },
    { bairro: "SANTO ANTONIO", doca: "24", itinerario: 14 },
    { bairro: "SAO JORGE", doca: "24", itinerario: 13 },
    { bairro: "SAO RAIMUNDO", doca: "24", itinerario: 14 },
    { bairro: "TARUMA", doca: "19/20", itinerario: 10 },
    { bairro: "TARUMA-ACU", doca: "19/20", itinerario: 10 },
    { bairro: "RAIZ", doca: "26", itinerario: 16 },
    { bairro: "ZONA RURAL", doca: "19/20", itinerario: 10 }
];

